services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file: /media/docker_volumes/.env
    volumes:
      - /media/docker_volumes/sonarr:/config
      - /media/libraries/tv:/tv
      - /media/usenet:/usenet
    restart: unless-stopped # Automatically restart Sonarr unless explicitly stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8989/sonarr/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - proxy

networks:
  proxy:
    external: true
